name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Laravel CI/CD Action
      uses: basantsd/laravel-ci-cd@v1
      with:
        production-branch: 'production'
        vps-host: ${{ secrets.LIVE_VPS_HOST }}
        vps-username: ${{ secrets.LIVE_VPS_USERNAME }}
        vps-private-key: ${{ secrets.LIVE_VPS_PRIVATE_KEY }}
        deploy-path: '/var/www/omenergy.app/'
        php-version: '8.3'

